// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKoe5nvP9M5mEkIKNMLkCQXWgqOKrneo',
    appId: '1:204903004802:web:df7a528cf9bcf26ba2d29b',
    messagingSenderId: '204903004802',
    projectId: 'serverpod-iot',
    authDomain: 'serverpod-iot.firebaseapp.com',
    storageBucket: 'serverpod-iot.appspot.com',
    measurementId: 'G-0GRBNCW0F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ct7khUIjqT1W7PLlfueTLqDrhqCGuO8',
    appId: '1:204903004802:android:09b5ed065eb14446a2d29b',
    messagingSenderId: '204903004802',
    projectId: 'serverpod-iot',
    storageBucket: 'serverpod-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChc6enDY5A1iJUFjDODgaCmtnJ4kqTfxo',
    appId: '1:204903004802:ios:7d3836e70c6b5142a2d29b',
    messagingSenderId: '204903004802',
    projectId: 'serverpod-iot',
    storageBucket: 'serverpod-iot.appspot.com',
    androidClientId: '204903004802-natl8f9or2j0s0v7uva28dbu0tp1is0g.apps.googleusercontent.com',
    iosClientId: '204903004802-i45vmu929qi2qduaqs0uffpoadi43hli.apps.googleusercontent.com',
    iosBundleId: 'com.example.mypodFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChc6enDY5A1iJUFjDODgaCmtnJ4kqTfxo',
    appId: '1:204903004802:ios:7d3836e70c6b5142a2d29b',
    messagingSenderId: '204903004802',
    projectId: 'serverpod-iot',
    storageBucket: 'serverpod-iot.appspot.com',
    androidClientId: '204903004802-natl8f9or2j0s0v7uva28dbu0tp1is0g.apps.googleusercontent.com',
    iosClientId: '204903004802-i45vmu929qi2qduaqs0uffpoadi43hli.apps.googleusercontent.com',
    iosBundleId: 'com.example.mypodFlutter',
  );
}
